version: '3'
services:
# Hello app
  app1:
    build: ./app
    ports:
      - "8082:8080"
    networks:
      - app-network
  app2: 
    build: ./app
    ports:
      - "8081:8080"
    networks:
      - app-network
    
#Nginx Service
  webserver:
    build: ./nginx
    ports:
      - "8080:8080"
    networks:
      - app-network
# Percona Mysql DB
  db:
    image: percona/percona-server:8.0
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - app-network
#Docker Networks
networks:
    app-network:
      driver: bridge
    


   